/* ============================================================
   MELANCHOLY FALLS — EPISODE 1: "PILOT"
   Script data. See docs/SCRIPTING.md for the format.
   Everything here is replaceable: art in assets/img, text here.
   ============================================================ */
'use strict';

/* ---------- characters ---------- */
const CHARS_TABLE = {
  bram:   {name:'BRAM',        color:'#8fb573', spr:'assets/img/spr_bram.png'},
  tues:   {name:'TUESDAY',     color:'#7db3e8', spr:'assets/img/spr_tuesday.png'},
  dex:    {name:'DEX LUXURY',  color:'#d9b36c', spr:'assets/img/spr_dex.png'},
  junie:  {name:'JUNIE',       color:'#c1a3d4', spr:'assets/img/spr_junie.png'},
  chad:   {name:'CHAD',        color:'#a3b1bc', spr:'assets/img/spr_chad.png'},
  brick:  {name:'BRICK',       color:'#d97e6a', spr:'assets/img/spr_brick.png'},
  ma:     {name:'MA',          color:'#e0b06e', spr:'assets/img/spr_ma.png'},
  pa:     {name:'PA',          color:'#a9a06b', spr:'assets/img/spr_pa.png'},
  grant:  {name:'PRINCIPAL GRANT', color:'#c98d8d', spr:'assets/img/spr_grant.png'},
  nurse:  {name:'NURSE BARGAIN', color:'#84b5ad', spr:'assets/img/spr_nurse.png'},
  narr:   {name:'NARRATOR (V.O.)', color:'#d8cfc0'},
  kid:    {name:'KID',         color:'#b9a58c'},
  dj:     {name:'DJ CHILLINGSWORTH', color:'#9db0c9'},
  goose:  {name:'GOOSE',       color:'#cfc7b4'},
  doc:    {name:'DOCTOR',      color:'#b0a1c0'}
};

/* ---------- backgrounds ---------- */
const BG_URLS = {
  kitchen: 'assets/img/bg_kitchen.jpg',
  street:  'assets/img/bg_street.jpg',
  creek:   'assets/img/bg_creek.jpg',
  school:  'assets/img/bg_school.jpg',
  mansion: 'assets/img/bg_mansion.jpg',
  otter:   'assets/img/bg_otter.jpg',
  gym:     'assets/img/bg_gym.jpg',
  quarry:  'assets/img/bg_quarry.jpg'
};

/* ---------- builders ---------- */
const bg   = id => ({bg:id});
const sp   = (id, slot='c', o={}) => ({sp:Object.assign({id,slot},o)});
const out  = id => ({out:id});
const fx   = k => ({fx:k});
const card = (name, sub, sting) => ({card:{name, sub, sting}});
const cut  = (label, nodes, bgid) => ({cut:{label, nodes, bg:bgid}});
const add  = m => ({add:m});
const flag = f => ({flag:f});
const lab  = id => ({label:id});
const go   = id => ({goto:id});
const IF   = (cond, then, els) => ({if:{cond, then, els}});
const END  = id => ({end:id});
const choice = (title, opts) => ({choice:{title, opts}});

const bram=t=>({w:'bram',t}), tues=t=>({w:'tues',t}), dex=t=>({w:'dex',t}),
      junie=t=>({w:'junie',t}), chad=t=>({w:'chad',t}), brick=t=>({w:'brick',t}),
      ma=t=>({w:'ma',t}), pa=t=>({w:'pa',t}), grant=t=>({w:'grant',t}),
      nurse=t=>({w:'nurse',t}), narr=t=>({w:'narr',t}), kid=t=>({w:'kid',t}),
      dj=t=>({w:'dj',t}), goose=t=>({w:'goose',t}), doc=t=>({w:'doc',t}),
      n=t=>({n:t});

const F = {
  drama: v=>add({drama:v}), susp: v=>add({susp:v}), bond: v=>add({bond:v}), cass: v=>add({cass:v})
};

/* ============================================================
   EPISODE 1 — "PILOT"
   ============================================================ */
const SCRIPT = [

/* ============ COLD OPEN ============ */
bg('black'),
card('MELANCHOLY FALLS', 'population: felt', true),
narr("There is a town called Melancholy Falls."),
narr("It sits in the fertile heart of—"),
fx('bell'),
narr("...The state will not be named. The state knows what it did."),
narr("Like every town, Melancholy Falls has secrets. Unlike every town, it has a quarry, which is where secrets go to be dropped."),
narr("Sixteen years ago, the sky broke."),
card('SIXTEEN YEARS EARLIER', 'the Drizzle of ’89', true),
bg('street'),
narr("They called it the Drizzle. Because 'shower' felt needy, and this town has its dignity."),
narr("Two things fell from the sky that night that should not have. The first was a baby."),
bg('kitchen'),
sp('ma','l1'), sp('pa','r1'),
narr("Gerald and Marjorie Wellington found him in the cornfield. Naked. Calm. Holding a briefcase."),
pa("Marjorie. There's a baby in the corn."),
ma("Then the corn has done well this year, Gerald."),
pa("He's holding a briefcase."),
ma("We'll raise him as our own."),
pa("With the briefcase?"),
ma("With the briefcase, Gerald. He came with it. It's a set."),
narr("The briefcase was empty. That was the problem. It has never not been the problem."),
out('*'),
narr("The second thing that fell was heavier. It found the Luxury family greenhouse."),
bg('mansion'),
card('YOUNG DEX LUXURY', 'eight years old, robe, juice', true),
narr("Young Dexter Luxury watched the sky fall on his mother's orchids. He did not cry. He took a sip of brandy."),
dex("(It's juice. I'm eight.)"),
narr("The meteor passed close enough to take his hair. All of it. In slow motion. Like a shampoo commercial played backward as a threat."),
fx('ping'),
narr("It also took his ability to shiver. He has not been cold since. He has not been warm since. He has been... room temperature. Forever."),
dex("Fascinating."),
narr("That was the whole sentence. He was a lot, even at eight."),
bg('black'),
card('EPISODE 1 — “PILOT”', 'the one where everything starts, obviously', true),
narr("Previously, on Melancholy Falls: nothing. This is the first one. We just like saying it."),

/* ============ ACT ONE: MORNING ============ */
lab('act1'),
bg('kitchen'),
narr("The Wellington farm. Sixteen years and one ongoing feud with a bank later."),
sp('bram','c'), sp('ma','l1'), sp('pa','r1'),
narr("Bram Wellington, seventeen, wakes the way all heroes wake: to a casserole placed outside his door like a newspaper."),
ma("That's a Number Six, sweetheart."),
bram("What's a Number Six?"),
ma("You know what a Number Six is."),
cut('THE CASSEROLE DICTIONARY', [
  bg('kitchen'),
  n("Every casserole is a sentence. Ma learned the language from her mother, who learned it from a war."),
  ma("Lasagna: your father lost the farm."),
  ma("Tater tot hotdish: the meteor insurance lapsed."),
  ma("Jell-O with a fork in it: someone died."),
  ma("Number Six — tuna, crushed crackers, one hard-boiled egg standing up — means: we need to talk, and I made food about it."),
  n("The egg standing up means it's serious. A lying egg means 'condolences.'")
], 'kitchen'),
add({cass:1}),
bram("A Number Six. On a Thursday."),
ma("Sit down, Bram. Your father wants to say something, and I wanted there to be tuna about it."),
pa("The Bank is sending a man to the Autumn Chills Dance."),
bram("The Bank has a table at a school dance?"),
pa("The Bank has a TABLE at a SCHOOL DANCE."),
fx('shake'),
narr("Pa said, as if this explained the shape of his life. It did not explain the shape of his life. Nothing will explain the shape of Pa's life."),
bram("Pa, you can't keep doing this. It's been eight years."),
pa("You don't know what the Bank took from me, Bram."),
bram("The east field."),
pa("The east FIELD, Bram. And my heart, which was also in the east field, physically, in a jar. Long story. Different night."),
narr("Every family in town has a 'different night.' Nobody has ever specified the night. This will become important, and then it won't."),
ma("Eat your feelings plate, dear. It's a Four."),
bram("A Four is 'weather's coming.'"),
ma("A Four is 'weather's coming,' yes."),
n("Bram sat, and ate, and then Ma did the one thing you must never do to a boy like Bram Wellington."),
fx('pushon'),
ma("We are so proud of you. Every day since the corn."),
bram("(a feeling)"),
fx('shake'),
narr("One feeling. That's all it takes. The toaster ascended."),
fx('ping'),
n("The toaster rose majestically past the window, past the birds, into the firmament. The Wellingtons watched it go, as one watches a son leave for college."),
pa("Feeling again?"),
bram("Little bit."),
pa("Aim it at the mailbox. It's been sassing your mother."),
ma("It said a word, Gerald. At me. In front of God."),
out('*'),
narr("And that is the thing about Bram Wellington, the thing this town will spend six episodes learning at great cost:"),
narr("when Bram feels something — anything — physics feels it too."),
narr("Joy: the cutlery hums. Grief: the truck floats. A single, sincere compliment can take out a gazebo."),
narr("He has never once been calm. He is a teenage boy. Calm is not on the menu. Calm was removed from the menu by the chef."),
bg('street'),
narr("Meanwhile: the walk to school. Golden hour. Everyone in this town is backlit. It's a condition."),
sp('junie','r1'),
card('JUNIE LAKE', 'narrates, out loud, cannot stop', true),
junie("I walked to school the long way. The creek understood me. The creek had always understood me. It's the only one who— Bram. You're in my narration."),
bram("Sorry."),
junie("'Sorry,' he said, like a man who had never once meant it."),
bram("I meant it."),
junie("He meant it, the narrator corrected, surprising no one more than himself."),
choice('HOW DO YOU HANDLE JUNIE?', [
  {t:"Step out of her narration, respectfully.", k:"the creek respects this", add:{bond:0, drama:2}, goto:'junie_a'},
  {t:"Narrate back at her, in her exact voice.", k:"two narrators, one sidewalk", add:{drama:6}, goto:'junie_b'},
  {t:"Say nothing. Let her fill the silence. She will.", k:"she always does", add:{drama:0, susp:0}, goto:'junie_c'}
]),
lab('junie_a'),
bram("I'll just— I'll walk over here. On the non-narrated side of the sidewalk."),
junie("He withdrew. The creek said nothing, which is how you know it was thinking."),
go('act1_school'),
lab('junie_b'),
bram("(gravely) He walked on. The sidewalk forgave him. It had forgiven so many."),
junie("Don't."),
bram("The creek glistened, like a man remembering a war."),
junie("Bram, we've talked about this. There is one narrator in this town, and she is TWELVE FEET FROM HER OWN HOUSE."),
add({drama:4}),
go('act1_school'),
lab('junie_c'),
n("Bram said nothing. Junie filled the silence for eleven minutes, which is the record. It still stands."),
go('act1_school'),

/* ---- school ---- */
lab('act1_school'),
bg('school'),
narr("Longing High School. Home of the Fighting Ambivalents."),
narr("The wrong side of the tracks runs through the middle of the school. The wrong side is the cafeteria. Everyone eats there anyway. It's complicated."),
sp('grant','c'),
card('PRINCIPAL SKYLER GRANT', 'Cliffhanger’s Disease — stable, for now', true),
grant("Attention, students. This morning... something happened."),
grant("We don't know what it was yet. But it happened... here. Or near here."),
grant("The relevant authorities have been notified. Or will be. That is all."),
grant("For now."),
fx('sting'),
out('*'),
narr("Principal Grant has Cliffhanger's Disease. He can only end sentences as cliffhangers. Doctors say he'll be fine. For now."),
narr("He has not completed a sentence since 2003. His wedding vows ran four hours and ended in a question. The marriage did not survive the season break."),
sp('chad','r2'),
card('CHAD MORGAN', 'in a coma since the pilot episode of our lives', true),
narr("By the trophy case: Chad Morgan. Been in a coma since 'the incident.' His bed is parked in the senior spot. He is wheeled to fourth period because attendance is a legal thing."),
nurse("(writing) The boy in bed three twitched his toes twice this morning. Both times, the vending machine dropped two free Sprites."),
nurse("The boy in bed three is a mood ring."),
out('*'),
narr("Nobody heard her say it. Nobody ever hears Nurse Bargain say anything. That is her power, and in season four it will be everyone's downfall."),
fx('whir'),
narr("And then — the sound every small town dreads. Not sirens. Not thunder. Rotor wash."),
sp('dex','l2'),
card('DEX LUXURY', '24, bald, owns the school’s air rights', true),
narr("Dex Luxury, arriving by helicopter, directly onto the tennis courts. He owns the school's air rights. He bought them in a poker game from a superintendent who thought 'air rights' was a bluff."),
dex("(over rotor wash) GOOD MORNING, LONGING HIGH! I have an announcement that is also a gift, which is the only kind I give!"),
out('dex'),
sp('dex','c'),
dex("This Saturday: the Autumn Chills Dance. I own 'chills' in this county. I own 'autumn' outright. The dance will be held in the gym, as is tradition, and as is load-bearing."),
kid("(whispering) He landed ON the tennis courts. Again."),
kid("Coach Pep is going to lose it. He's still finding helipunk in the ball machine."),
dex("There will be a banner. There is every year a banner. I have seen it. It is my favorite object in this county, and I once owned a diamond that could argue."),
out('dex'),
narr("And then the doors opened, and the year began."),
bg('school'),
fx('sting'),
narr("She walked in slow motion. Everyone walks in slow motion here — it's the water table — but she did it FIRST."),
sp('tues','c'),
card('TUESDAY WINTERS', 'new in town. city shoes.', true),
kid("(whispering) She has city shoes."),
kid("(whispering) Those shoes have seen TARGETS. Plural."),
tues("Hi. I'm looking for the office. And also the quarry, the creek, the meteor field, and whatever happened in this town on a night I won't specify yet."),
bram("The office is—"),
n("Bram Wellington felt a feeling. It was a big one. It had layers. There was a core of it that no one had ever named."),
fx('shake'),
fx('ping'),
narr("Across the parking lot, the flagpole bent — slowly, lovingfully — into the shape of a question mark."),
narr("Which was also how Bram felt."),
out('tues'),
sp('tues','r1'), sp('dex','l1'),
dex("You bent my flagpole."),
bram("Your flagpole?"),
dex("I've watched that pole for years, hoping it would bend. I've paid men to bend it. You did it with your FACE. You've made me feel... entertainment. I haven't been entertained since the mime trial."),
dex("Bram Wellington. Saturday. The Autumn Chills Dance. Be there, and feel things at me."),
out('dex'),
narr("This is how it started. The way all great tragedies start: with a dance, a banner, and a rich man who cannot shiver."),
out('*'),
sp('tues','c'),
tues("(into tape recorder) Day one. I've found him. Or someone like him. The town smells like corn and secrets. Also, someone's toaster went by overhead at 7:40 A.M. Logging it."),
tues("(click)"),
out('*'),

/* ============ ACT TWO ============ */
lab('act2'),
bg('creek'),
narr("The Creek. Where this town does its feeling. It has its own parking. The parking is never full, and yet, somehow, always contested."),
sp('junie','r1'),
narr("That evening, Bram did what everyone in Melancholy Falls does with a problem too big for a kitchen: he brought it to the water."),
bram("The new girl asked me for directions and I bent public infrastructure, Junie."),
junie("He came to the creek. He always came to the creek. The creek charged no rent and asked no questions. It was, in every way, his therapist."),
bram("Please don't narrate this one."),
junie("'Please,' he begged. The creek begged nothing. The creek had a system."),
bram("What do I do about Tuesday?"),
junie("Secrets are like canoes."),
n("(pause)"),
junie("I don't have an ending for that. I just saw a canoe."),
cut('THE TIME BRAM ARM-WRESTLED A HORSE', [
  bg('street'),
  n("Last summer. The county fair. The horse's name was District Attorney."),
  brick("Nobody's ever beat the District Attorney! He's undefeated! He's UNTIED! He's— those are different words, but he's BOTH."),
  bram("It's fine. I'm calm. I'm not even a little calm."),
  n("The Feels took the table apart. The horse went down in four seconds and stood back up a CHANGED animal."),
  n("They exchange a nod in the hallway now. Nobody discusses it. The horse sends a card at the holidays.")
], 'street'),
choice('TUESDAY IS ASKING QUESTIONS. YOUR MOVE?', [
  {t:"Keep it boring. Boring is armor.", k:"drama −, suspicion −", add:{drama:0, susp:-8}, goto:'crk_a'},
  {t:"Be mysterious. Lean on the fence. Say 'this town' a lot.", k:"drama +, suspicion +", add:{drama:12, susp:10}, goto:'crk_b'},
  {t:"Tell Junie the actual truth.", k:"the creek can handle it", add:{drama:6, bond:4}, goto:'crk_c'}
]),
lab('crk_a'),
bram("If I'm nothing, nothing floats. From now on I'm a man with no interior life. I'm Pa at a bank meeting."),
junie("He vowed to become boring. The creek had heard this vow before. The creek kept the receipts."),
IF(()=>S_meters().drama>=50,
 [ junie("But the town felt the vow land. Dramas raised. Somewhere, a chair turned to face a window."),
   fx('rainon'), n("It began to rain on one specific boy, as is custom."),
   bram("(at the sky) IT'S THE WRONG NIGHT FOR THIS."), fx('rainoff') ], []),
go('act2_dex'),
lab('crk_b'),
bram("This town has secrets, Junie. And some secrets... are better left—"),
junie("—on the other side of the tracks? Say it. Everyone says it. The tracks are RIGHT THERE, Bram, they go through the CAFETERIA."),
bram("Fine. Some secrets are better left on the other side of the cafeteria."),
junie("He chose mystery. Mystery is just lying with posture."),
add({susp:4}),
go('act2_dex'),
lab('crk_c'),
bram("The truth is I can't touch a feeling without the whole room finding out about it. Literally. The furniture finds out."),
junie("He said it out loud, finally. The creek did not gasp. Creeks have seen everything. That's the whole deal with creeks."),
junie("So tell the Tuesday girl. Worst case, she's from a family of insurance adjusters. Everyone here is from a family of insurance adjusters. It's a town of CLAWBACK."),
junie("(walking him home, quieter) Your ma dropped off a Number Eight this morning, by the way. In our shop. For my mom."),
bram("What's a Number Eight?"),
junie("'A boy is going to be stupid at a dance. Let him.' Yours has a sub-crust message, Bram. They only do the sub-crust for family."),
add({cass:1}),
go('act2_dex'),

/* ---- mansion ---- */
lab('act2_dex'),
bg('mansion'),
narr("The Luxury estate. The hedge maze is shaped like a hedge maze, which Dex calls 'irony,' which is not what that is."),
sp('dex','c'),
dex("Bram! You came. Would you like to fence?"),
bram("You don't have a partner."),
dex("I have a Roomba."),
cut('THE ROOMBA DUEL', [
  bg('mansion'),
  n("Every morning. En garde. The Roomba has heart. It has taken a rib from Dex — accidentally, medically — and wears a tiny bell."),
  dex("It fights like a cardsharp's grandmother. I've lost eleven mornings to it."),
  dex("The trick is it can't be baited. It has no emotions, only SCHEDULE.")
], 'mansion'),
dex("Come. I want to show you my collection."),
n("He led Bram to a display case. Inside: nine meteorite fragments, arranged on velvet, each lit like a museum piece. The label read: MY HAIR."),
bram("The label says—"),
dex("MY HAIR. Yes. Every fragment took a portion. I keep them together. It's a reunion, in a sense. A get-together. A salon, if you will."),
bram("I won't."),
dex("You won't what?"),
bram("Nothing."),
fx('ping'),
dex("Sit. Let me tell you about the Drizzle, Bram. The night the sky opened. THAT night."),
n("Note: no two people in this town mean the same night when they say THAT night. Nobody has noticed. It's like a town-wide sharehouse of the mind."),
dex("The meteors took my hair. My mother's greenhouse. My ability to shiver. Do you know what it's like to never shiver, Bram? To be, forever, room temperature?"),
fx('pushon'),
dex("Sweaters do NOTHING for me. Cocoa is a BEVERAGE. I stood in the freezer section at the Kroger's— at the— the store, and felt NOTHING, Bram. Nothing but priced and organized."),
choice('DEX JUST BARED HIS ROOM-TEMPERATURE SOUL.', [
  {t:"'I'd shiver for you, Dex.'", k:"an alliance is born", add:{drama:8}, flag:'dex_friend', goto:'dex_a'},
  {t:"'You should meet my friend the horse.'", k:"he means the District Attorney", add:{drama:2}, goto:'dex_b'},
  {t:"Slowly back out of the mansion. Sideways.", k:"crab-walk of destiny", add:{drama:0, susp:4}, goto:'dex_c'}
]),
lab('dex_a'),
dex("...No one has ever offered me a shiver."),
dex("When I rebuild the greenhouse — and I will, Bram, it's going to have a MOAT — I'm naming a wing after you. The Bram Wing. It'll be the one that feels things."),
n("Elsewhere in the county, a horse lifted its head, sensing an alliance."),
go('act2_otter'),
lab('dex_b'),
dex("I HAVE met the District Attorney. We correspond. He sends hay. I send money. It's the healthiest relationship either of us has ever had."),
go('act2_otter'),
lab('dex_c'),
n("Bram executed a full lateral exit. In Melancholy Falls this is considered polite. It means 'I have feelings I cannot afford to show.' Dex watched him go, moved."),
dex("(to himself) He moves like a crab. Crabs have SECRETS."),
add({susp:4}),
go('act2_otter'),

/* ---- the Drowsy Otter ---- */
lab('act2_otter'),
bg('otter'),
narr("The Drowsy Otter: Bait & Scone. One counter, two destinies. On the left, nightcrawlers. On the right, scones. In the middle, Junie's family, refusing to choose."),
sp('tues','c'),
card('TUESDAY WINTERS', 'day four. still new.', false),
tues("Bram Wellington. Sit down. I have a binder."),
bram("You have a binder."),
tues("I have a binder and I'm not afraid to use it. This town has had sixteen years of anomalies, Bram. I've catalogued them. SIT."),
n("Bram sat. Chairs have never been so serious."),
tues("Exhibit one. January: a cow predicts hail. The cow is never wrong. The cow is consulted now by the county. The cow has an OFFICE."),
cut('THE HAIL COW', [
  bg('street'),
  n("Her name is Registrar. She works Tuesdays and Thursdays. There's a line."),
  pa("Beggin' your pardon, Registrar. Hail this week?"),
  n("The Registrar stares at him for a long time. Then she does nothing. It's the right answer. It's ALWAYS the right answer."),
  n("Three towns over, a man ignores the nothing. His azaleas are now a rumor.")
], 'street'),
tues("Exhibit two. The man who is forty percent soup."),
bram("Hot tub incident. He's fine. He's broth now. He's BELOVED, Tuesday. He emcees the dance."),
cut('THE SOUP MAN', [
  bg('otter'),
  n("Forty percent. From the waist down. He calls it 'the bisque.'"),
  ma("More bread, dear? Bread helps the bisque."),
  doc("Medically, the bread does nothing. Spiritually, the bread does everything.")
], 'otter'),
tues("Exhibit three. Indoor rain. At the Kowalski funeral. Rain INSIDE. On one pew."),
cut('THE INDOOR FUNERAL RAIN', [
  bg('otter'),
  n("It rained indoors on exactly one pew. The family declined to move. The town declined to ask."),
  ma("(quietly) Someone has feelings and good aim."),
  n("The vicar said it was a blessing. The vicar then opened an umbrella, indoors, which cancelled the blessing, theologically. It's a whole thing.")
], 'otter'),
tues("Exhibit four. Sixteen years of toast- ascension events. Sixteen years of flagpole incidents, all UNSIGNED. And now, this week: MY PEN FLOATS AT YOU."),
tues("So. Bram Wellington. What is going on in this town?"),
fx('sting'),
choice('THE BINDER IS OPEN. THE PEN IS HOVERING. TALK.', [
  {t:"'Meteorites in the water table. It's a known thing. Look it up.'", k:"a lie with a bibliography", add:{susp:12, drama:4}, goto:'ott_a'},
  {t:"'I can't talk about it. Especially not near windows.'", k:"mystery with posture", add:{drama:10, susp:6}, goto:'ott_b'},
  {t:"'Sometimes, when I feel things... furniture also feels things.'", k:"a half-truth. the honest kind.", add:{bond:14, susp:-4, drama:2}, goto:'ott_c'}
]),
lab('ott_a'),
tues("The water table. Hmm. HMMMM."),
n("Tuesday wrote 'WATER TABLE??' in the binder, underlined it three times, and then — Bram watched this happen — underlined the underlines."),
tues("This is going in Volume Two."),
add({susp:4}),
go('act2_ma12'),
lab('ott_b'),
tues("'Near windows.' Noted. Windows admitted to the record."),
n("She drew a small window in the binder, and a small arrow, and the small arrow pointed at Bram."),
go('act2_ma12'),
lab('ott_c'),
n("The pen landed. The binder closed. Something in the room went from 'interrogation' to 'sitting with a friend at a bait counter, near the scones.'"),
tues("(quieter) My family doesn't run FROM the weird stuff, Bram. Never once. We move TOWARD it. We've moved eleven times."),
tues("You'll understand that eventually, and when you do, it's going to be at the worst possible moment. That's just how we do things."),
IF(()=>S_meters().bond>=30, [ junie("(from the counter) 'Eventually,' she said. The creek — fifty feet away, but PRESENT — agreed.") ], []),
go('act2_ma12'),

/* ---- casserole twelve ---- */
lab('act2_ma12'),
bg('kitchen'),
sp('ma','c'),
narr("Friday. The night before the dance. Bram came home to find a casserole on the porch railing. Standing beside it, like an honor guard: a second, smaller casserole."),
ma("Number Twelve."),
bram("Which is?"),
ma("Bram Wellington. Number Twelve is 'your father wants to talk to you at the dance, in front of people, and I made food about it so you can't be mad.'"),
add({cass:1}),
bram("That's a lot for tuna to carry, Ma."),
ma("It's not tuna. Twelve is CHICKEN. Chicken is the heaviest of the proteins. You know this."),
fx('thunk'),
n("The little casserole, the honor guard, was a Two. 'Wear the flannel with the good buttons.' Ma had thought of everything."),
out('*'),
sp('chad','r2'), sp('nurse','r1'),
narr("Meanwhile — the school, after hours. The trophy case. The boy in bed three."),
nurse("(writing) 9:47 P.M. All toes, both feet, forty-one minutes straight. Something in this town is having a very large week."),
nurse("Saturday is the dance. The dance is in the gym. The gym is over the quarry."),
fx('sting'),
nurse("(writing) If tomorrow goes the way this town goes, I should pre-chill a stretcher."),
nurse("God, I love this job."),
out('*'),

/* ============ ACT THREE: THE DANCE ============ */
lab('act3'),
bg('gym'),
narr("Saturday. The Autumn Chills Dance. The gym was decorated 'rustic elegant,' which in this town means corn, but up."),
sp('junie','l1'),
junie("The banner said AUTUMN CHILS. The L had fallen at 4 P.M. and would not be rehung. It had become a metaphor, which the decorating committee refused to address."),
out('junie'), sp('brick','c'),
card('BRICK STONE', 'quarterback. quarry heir. puncher of bowls.', true),
narr("Brick Stone surveyed the punch. The punch had done nothing. The punch had never done anything to anyone."),
brick("Somebody's gotta keep it honest."),
fx('shake'),
n("Brick punched the punch. The punch took it like a professional. This is the third year running. The bowl is ceramic, the bowl is a veteran, and the bowl will outlive us all."),
out('brick'), sp('tues','r1'), sp('bram','c'),
dj("GOOD EVENING, LONGING HIGH. DJ CHILLINGSWORTH HERE. IT IS NOW LEGALLY AUTUMN. THIS ONE GOES OUT TO THE NEW GIRL. IT'S CALLED 'TUESDAY'S SONG.' IT'S BY THE SENSITIVE DADS."),
fx('pushon'),
n("They danced. Slowly. Under the banner that was missing its L. In a town with no state and a gym with no floor inspection certificate."),
n("And it was nice. That was the problem. It was nice, and Bram felt it, and—"),
fx('ping'),
fx('sting'),
sp('chad','l2', {jolt:true}),
card('CHAD MORGAN', 'awake. unfortunately.', true),
narr("Sixteen feet away, in a hospital bed parked by the trophy case, Chad Morgan — coma patient, local landmark, bed three — opened his eyes."),
chad("IT'S HIM."),
n("The record skipped. DJ Chillingsworth stopped the music. Two hundred teenagers turned around. The punch, veteran of a thousand fists, rippled."),
chad("THE FEELINGS. THEY COME FROM HIM. THE TOES KNEW. THE TOES ALWAYS KNEW."),
fx('sting'),
bram("Chad—"),
chad("I've been AWAKE for like forty percent of it, man! You think a coma's quiet? I've had sixteen years of your HOMEWORK anxiety! I know how the treaty of Ghent ends! I have OPINIONS about your MOTHER'S SINGING!"),
chad("I'M NOT EVEN MAD ABOUT THE COMA. I'M MAD THAT I DID IT AT THE PILOT EPISODE OF OUR LIVES AND NOBODY—"),
n("History will disagree about what happened next. Here is what the seismograph says:"),
fx('crash'), fx('shake'),
n("The gym floor — the gym that is built, in defiance of God and zoning, directly over the quarry — opened like a book."),
n("Two hundred students stepped back. Chad Morgan, sixteen years in a bed, one minute awake, did not."),
chad("...oh, COME ON—"),
fx('crash'),
out('chad'),
n("Chad Morgan fell into the quarry. Again. For the second time in his life. The first time was the pilot episode of our lives, and we've never gotten details, and now the sequel is happening in real time."),
kid("(from the crowd) THE BED FLOATS? THE BED FLOATS. EVERYTHING IN THIS TOWN FLOATS EVENTUALLY."),
fx('rainon'),
n("It began to rain. Indoors. On the gym. On everyone, this time."),
n("Drama, as a substance, had reached its flash point."),
IF(()=>S_meters().drama>=70,
 [ n("The Drama Meter — which this town maintains, officially, at the post office — had overflowed."),
   grant("(grabbing the mic) This... is the most dramatic thing... that has ever happened here. Or anywhere. Tonight."),
   grant("For now."),
   fx('sting') ], []),
lab('rescue'),
bg('quarry'),
narr("The quarry. Everyone at the edge. Chad, far below, in his bed, which had somehow landed upright and was, in the way of hospital beds, still raising its own rails."),
chad("(up) I'M OKAY! THE BED'S OKAY! THE IV POLE IS A LITTLE BENT! IT'S BENT INTO A QUESTION MARK, WHICH, GIVEN EVERYTHING—"),
brick("(honestly moved) He's so strong."),
tues("Bram. If you're going to do whatever it is you do — and I'm not saying you do anything, but my pen is doing THIS—"),
n("her pen, hovering, doing this"),
tues("—now would be the time."),
bram("I can't. I feel too much. If I go down the side of this quarry feeling like THIS, I'll take the whole quarry with me. I'll take the COUNTY."),
pa("(arriving, out of breath, holding a casserole) NUMBER ONE! NUMBER ONE, SON!"),
ma("It means RUN."),
fx('thunk'),
tues("Bram. Look at me. Appendix C. Page 401."),
bram("What's Appendix C?"),
tues("Boring Facts. For Emergencies. My family has never once had a non-boring emergency. READ IT WITH ME."),
tues("The dot over an 'i' is called a tittle."),
bram("...the dot over an 'i' is called a tittle."),
tues("Crayons are mostly paraffin."),
bram("Crayons are... mostly paraffin."),
tues("There are one hundred and eighteen confirmed elements and every one of them is fine with that."),
bram("There are one hundred and eighteen confirmed elements... and every one of them... is fine with that."),
n("And so it went. Appendix C. The anvil of the mind. Bram Wellington, seventeen, felt his interior life — the corn, the creek, the flagpole, the girl with the binder, the horse — go quiet, like a bar at closing."),
n("By 'the air speed velocity of an unladen Cornish' he was calm. At 'soup is a beverage legally, in this state—'"),
 fx('bell'),
 n("—in THIS state, church bells, right, noted—"),
n("—at that point, Bram Wellington was the calmest object in the tri-county area."),
fx('pushon'),
n("He went down the quarry wall like a man descending into a quarry to pick up a bed. No feelings. No Feels. His face was the face of a man doing taxes in 1997."),
n("He took the bed under one arm. He climbed. He passed the IV pole, which he straightened, with two fingers, absently, like it was a picture frame."),
n("Rain does not fall on a man that calm. The rain, seeing him, stopped out of respect."),
fx('rainoff'),
bg('gym'),
sp('chad','c'), sp('bram','l1'), sp('tues','r1'), sp('grant','r2'),
n("Bram set Chad down at the edge of the dance floor, among the corn decorations, under the banner that said AUTUMN CHIL."),
chad("(quietly) So that's what outside looks like. Mid."),
grant("(into the mic) Ladies and gentlemen... a rescue. But was it? An ordinary... rescue?"),
grant("For now."),
n("Two hundred teenagers looked at Bram. Then at the bent flagpole through the window. Then at the pen, still doing this. Then at the floating dessert table, which by then had become a flock."),
n("Tuesday looked at Bram. In a way that said: your move, corn boy."),

/* ---- the climax ---- */
lab('climax'),
choice('THE WHOLE TOWN IS WATCHING. THIS IS THE ONE THEY’LL RECAP NEXT WEEK.', [
  {t:"Take the DJ mic. Tell them everything.", k:"the truth, at dance volume", add:{drama:10}, goto:'end_truth'},
  {t:"Walk out. To the creek. Tell ONE person.", k:"the creek can keep a secret", add:{bond:10, drama:4}, goto:'end_creek'},
  {t:"Point at the window and yell 'GOOSE!'", k:"the town needs this. the town WANTS this.", add:{drama:6, susp:-20}, goto:'end_goose'},
  {t:"Do what Ma would do.", k:"requires knowing 3+ casserole meanings", if:()=>S_meters().cass>=3, add:{drama:2}, goto:'end_casserole'}
]),

/* ---- ENDING A: TRUTH ---- */
lab('end_truth'),
bg('gym'),
sp('bram','c'),
bram("(into the mic) My name is Bram Wellington. Sixteen years ago I fell out of the sky into a cornfield, holding a briefcase, and ever since, whenever I feel a feeling, the furniture also feels it."),
bram("The flagpole? Mine. The toaster? Also mine. The funeral rain was — okay, that one wasn't me, but it's a cousin, and I'll be speaking to them."),
n("Silence. Two hundred teenagers. The soup man, emceeing by the door, set down his microphone."),
kid("(from the crowd) ...the soup guy votes yes."),
kid("(from the crowd) The soup guy's vote is binding! EVERYONE KNOWS THAT!"),
fx('sting'),
n("The town cheered. Of course they cheered. They had a hail cow and a soup man and a horse with a public office. They had been WAITING for this. They were FULLY STOCKED on acceptance."),
n("In the back, alone, Dex Luxury began to clap. Slowly. It is the only way he claps. He learned it from a villain in a film and it is, genuinely, the only thing he took from that film."),
dex("(to himself, delighted) A hero. In MY county. Room temperature is a choice... and I choose THIS."),
grant("(into the mic) Tonight... this town got exactly what it needed."),
grant("Or did it need... something else?"),
grant("...For now."),
bg('black'),
card('TO BE CONTINUED', 'and we mean it this time', true),
narr("Principal Grant drove home. He parked. He sat in the driveway for a while, in the dark, the way he always did."),
narr("“Today,” he said to no one, “a boy became a man.”"),
narr("“Or did he.”"),
narr("“...For now.”"),
fx('scratch'),
END('truth'),

/* ---- ENDING B: CREEK ---- */
lab('end_creek'),
bg('creek'),
sp('bram','l1'), sp('tues','r1'),
n("He didn't take the mic. He looked at Tuesday, and Tuesday — binder under her arm, pen finally, blessedly still — followed him out."),
n("They walked to the creek. It was going to understand. That's the whole arrangement with the creek."),
bram("You had a page for this. Appendix D, probably."),
tues("Appendix D is blank. It's for what people tell you when they're ready. I've moved eleven times, Bram. Appendix D has never once been written in."),
bram("Then here. When I feel things, physics feels things. Big things. That's the flagpole. That's the toaster. That's everything in the binder that isn't a cow."),
n("Tuesday set the binder down on the creek bank. The creek did not take it. The creek has manners."),
tues("You want to know why my family moves toward the weird?"),
tues("Because of this."),
n("She handed him a photograph. It was the size of a school photo. It was, unmistakably, a goose."),
bram("This is a goose."),
tues("That's me, Bram. Second grade. Every photograph ever taken of me is a slightly different goose. School pictures. Passport. My grandmother's funeral. GOOSE. My family didn't run from the weird, and they didn't run toward it either. They just refused to make me live like it was a problem."),
tues("So we move. Toward places that already have a weird thing going on. So I'm not the weird thing."),
fx('pushon'),
tues("Then this town got a DRIZZLE, Bram."),
tues("I've never been the only goose in a town before."),
IF(()=>S_meters().bond>=40,
 [ bram("Tuesday Winters. I fell out of the sky holding a briefcase. You photograph as waterfowl. If we're being honest, this town has a TYPE, and we're it."),
   tues("(laughing, wet-eyed, furious about it) Appendix D. Write it down. APPENDIX D IS OPEN."),
   n("The creek, as is custom, understood.") ],
 [ bram("Then be weird here. We've got a quota to fill and I can't do it alone."),
   tues("(quietly) Appendix D. It's open. Don't make it weird."),
   n("Too late. It's a whole town of it.") ]),
bg('black'),
card('TO BE CONTINUED', 'sincerely — we mean it', true),
narr("Principal Grant drove home. He sat in the driveway. In the dark."),
narr("“Tonight,” he said, “two freaks decided to be weird at each other on purpose.”"),
narr("“Or was it... love.”"),
narr("“...For now.”"),
fx('scratch'),
END('creek'),

/* ---- ENDING C: GOOSE ---- */
lab('end_goose'),
bg('gym'),
sp('bram','c'),
n("There are moments that define a man. This was not one of them. This was the other kind."),
bram("(pointing out the window) GOOSE!"),
n("Every head turned. And there — because there is always, ALWAYS a goose — there it was. Standing on the helipad lines Dex had painted on the tennis courts. Standing like it had done something. Standing like it KNEW."),
fx('sting'),
kid("(from the crowd) THE GOOSE DID IT."),
kid("(from the crowd) The flagpole. The toaster. Sixteen years of FLOATING BREAD. IT WAS THE GOOSE ALL ALONG."),
n("The town needed this. The town wanted this. The town has a boxing tradition of believing geese, and by Tuesday the goose had been arrested, arraigned, and photographed for the paper doing a perp walk in tiny handcuffs."),
n("It did the walk in slow motion. They all do. It's the water table."),
bg('street'),
card('GOOSE', 'did it', true),
goose("(honk)"),
n("The goose retained a public defender. The public defender has never lost a case and has never won one either; every trial ends in a mistrial because the witness stand is 'emotionally upstream.'"),
n("Bram Wellington, meanwhile, was free. Free, and brooding. He started sitting on the wrong side of the cafeteria tracks. He got a leather cord necklace. He began saying 'this town' with a little pause before it."),
junie("He changed. The creek logged the change. The creek filed no complaint. The creek is not a snitch."),
bg('black'),
card('TO BE CONTINUED', 'dark bram rises', true),
narr("Principal Grant drove home. He sat in the driveway."),
narr("“Tonight,” he said, “a boy blamed a bird. And the bird... took it.”"),
narr("“Where does a goose go, when it takes the fall for a man?”"),
narr("“...For now.”"),
fx('scratch'),
END('goose'),

/* ---- ENDING D: CASSEROLE (secret) ---- */
lab('end_casserole'),
bg('quarry'),
sp('bram','c'), sp('chad','r1'),
n("Bram Wellington stood before the town, and the truth rose in him — the whole truth, the corn, the sky, the briefcase — and then he thought: what would Ma do?"),
n("Ma would make food about it."),
bram("Chad Morgan. Sixteen years in that bed. One minute awake. I owe you a casserole."),
n("He opened the foil. Number Nine. Tuna. Crushed crackers. And one hard-boiled egg, standing up, because it was serious."),
ma("(from the crowd, softly) Number Nine. 'I have powers, and I love you.'"),
fx('thunk'),
chad("(staring at it) ...you knew?"),
bram("Ma ran the numbers. Ma always runs the numbers."),
n("Chad Morgan, coma patient, quarry survivor, took the casserole in both hands, and ate it, standing up, at the edge of a quarry, in the rain, like a man accepting an apology from the sky."),
chad("(chewing) It's just — I saw everything, you know? Everything. Sixteen years of it. Homework. Funerals. Your mom singing. The treaty of Ghent, twice."),
chad("You don't sleep through that and come out the other side REGULAR, Bram."),
chad("(hands him the empty dish) Wake me when it's over."),
n("And Chad Morgan — voluntarily, deliberately, with the serenity of a man who has seen the pilot AND the finale — climbed back into the bed, and closed his eyes."),
fx('sting'),
n("The town said nothing. The town had watched a boy hand another boy a casserole, and watched that casserole end a sixteen-year medical event, and the town — the hail cow, the soup man, the horse with the office, all of them — understood it completely."),
n("It's a language. Everyone here speaks it. Nobody taught it. That's a town for you."),
n("In the crowd, Ma wiped her hands on her apron, once, like a surgeon closing."),
ma("(to Pa) He's ready for Number Fifteen."),
pa("What's Number Fifteen?"),
ma("The future, Gerald. Number Fifteen is the future."),
bg('black'),
card('TO BE CONTINUED', 'the casserole knows the way', true),
narr("Principal Grant drove home. He sat in the driveway, engine off, in the dark, in the quiet."),
narr("“Tonight,” he said, “a casserole did what medicine could not.”"),
narr("“Or... was the casserole medicine all along?”"),
narr("He looked at the house. The porch light was on. Marjorie — no, HIS Marjorie, the one before the disease — used to leave it on like that."),
narr("“...For now,” he said. And went inside."),
fx('scratch'),
END('casserole')
];

/* ---------- endings table ---------- */
const ENDINGS = {
  truth: { name:'THE PROM KING OF TRUTH', body:'Bram told the whole town, at dance volume. The town, fully stocked on acceptance, shrugged and cheered. The soup guy voted yes, and the soup guy’s vote is binding.',
           hint:'take the DJ mic and tell them everything' },
  creek: { name:'THE CREEK PACT', body:'Bram told one person, at the creek. She countered with a photograph of a goose. The two most dangerous freaks in the county agreed to be weird at each other on purpose.',
           hint:'walk out and tell Tuesday, privately' },
  goose: { name:'THE GOOSE ALIBI', body:'Bram blamed a goose. The town needed this. A goose was arrested and did its own slow-mo perp walk. Bram got a leather cord necklace and a pause before “this town.”',
           hint:'when in doubt: point at the window' },
  casserole: { name:'THE CASSEROLE', body:'SECRET ENDING. Bram did what Ma would do. Casserole Number Nine: “I have powers, and I love you.” Chad ate it, forgave everything, and went back into his coma on purpose. Wake him when it’s over.',
           hint:'be honest at the creek, learn the casseroles, then do what Ma would do', lockHint:'the casseroles have more to teach…' }
};

/* ---------- state accessors used by script conditions ---------- */
/* The engine overwrites these hooks after load, so IF() conditions in the
   script can read live meters/flags without touching engine internals. */
const MF_HOOKS = { getMeters: ()=>({drama:0,susp:0,bond:0,cass:0}), getFlags: ()=>[] };
function S_meters(){ return MF_HOOKS.getMeters(); }
function S_flags(){ return MF_HOOKS.getFlags(); }

/* ---------- collect cutaways for the gallery ---------- */
const CUTAWAYS = SCRIPT.filter(nd=>nd && nd.cut).map(nd=>nd.cut);

/* engine hooks: engine overrides these two after load */
